### ISSUE TITLE
Fix the range function

### ISSUE THREAD

**Issue by YangF0917** [StRobertCHS-ICS4U1a-201819/tdd-git-assignment-felix-and-casey#3]
@lij1201 The range function should find the largest number in the list subtracted by the smallest number in the list

**Comment by lij1201** [comment]
But isn't that what I did @YangF0917

**Comment by lij1201** [comment]
I sort the list first from smallest to biggest and then use the last one in the list and subtract it by the first one in list @YangF0917

**Comment by YangF0917** [comment]
Yea for whatever reason mine didnt have the sort
